### ISSUE TITLE
Crash/bug

### ISSUE THREAD

**Issue by Lucos5** [focustense/easymod#106] opened 2021-09-01 05:21 UTC
I was trying to use this for the first time. Popped up when building
[Log_20210901_011214_3910806.txt](https://github.com/focustense/easymod/files/7088446/Log_20210901_011214_3910806.txt)

**Comment by focustense** [comment] 2021-09-01 15:39
Dupe of #105. You can use the workaround I suggested there to get around the exception, but you likely have some problem that is similar to his - since the app is not finding any facegens to copy, it suggests that the mod directory is invalid or that something else is misconfigured.

**Closed** 2021-09-01 15:39 UTC
Labels: duplicate, easynpc

**Comment by focustense** [comment] 2021-09-01 19:08
Only one workaround, which is creating the directory manually.

I doubt it will actually give you a valid/working merge, given current evidence about the root cause - it just solves that particular error.

**Comment by Lucos5** [comment] 2021-09-03 02:31
yeah, I made a new folder and told vortex that it is the new folder, it moved the mods over but it is still giving that issue, did I do anything wrong?

**Comment by focustense** [comment] 2021-09-03 12:57
You can move your mods folder on disk, but then you have to update the mod directory setting in EasyNPC. Otherwise you now have it pointing to an empty directory and that's why it's not finding anything to copy.
