### ISSUE TITLE
"Something went wrong" error at plugin selection

### ISSUE THREAD

**Issue by Cthulyn** [focustense/easymod#112] opened 2021-09-05 00:11 UTC
Disclaimer: I've been a bit under the weather lately (severe vertigo) so there's a good chance I've done something stupid or missing an obvious solution to this issue...

I followed the Getting Started Guide & was initially able to create a compilation (which took forever to save), but ran into a few blackfaces, so I made adjustments, uninstalled the first version, built and activated a second. No errors, game even seemed to load faster than before, but somehow wound up with several more NPCs with blackface or the "wrong" face. 

I figured it must have something to do with my other mods so I switched out a few and attempted to create a third compilation, but the program froze (Not Responding) & ever since I can't get past the "Confirm plugin selection" screen, getting "Something went wrong" every time. I tried deactivating the new mods, deactivating any type of "patch" and even manually selecting ONLY the NPC & related plugins (about 30 out of 169), same error.

I've attached the last few Log files (I somehow wound up with 14 of them just from today) but I can provide more if needed. 

Please let me know if I missed a step or if there's an article to troubleshoot this issue (I couldn't find anything in the guides or FAQs). Any assistance would be greatly appreciated!

[Log_20210904_142641_8244867.txt](https://github.com/focustense/easymod/files/7110666/Log_20210904_142641_8244867.txt)
[Log_20210904_143559_6327949.txt](https://github.com/focustense/easymod/files/7110667/Log_20210904_143559_6327949.txt)
[Log_20210904_195452_0000840.txt](https://github.com/focustense/easymod/files/7110668/Log_20210904_195452_0000840.txt)

**Comment by focustense** [comment] 2021-09-05 00:31
As far as loading EasyNPC is concerned, you've run into #103. Definitely not obvious, it was a regression in version 0.9 that didn't get caught for about a week. I should be putting out a new release in the next day or two that will eliminate that issue, but sadly it can't fix profiles that are already corrupted, so you'll have to follow the workarounds there regardless in order to fix it. If you've already exported a profile, easiest would just be to delete profile.log and start over, then import your profile again using the affinity workaround.

Approximately 100% of blackface issues are due to conflicts from leaving mods enabled after the EasyNPC merge is done. I have, so far, never seen a confirmed case from any other cause. Disabling the source overhauls afterward is not an optional step, especially if they use loose files, it has to be done. You're going to have some files in `meshes\actors\character\facegendata`, and you'll want to find out which mods are providing those files, and disable them. If you can't disable them due to master dependencies, there's a [FAQ dedicated to resolving that](https://github.com/focustense/easymod/blob/master/Focus.Apps.EasyNpc/Docs/faq.md#my-mod-has-dependencies-on-the-original-overhauls-isnt-easynpc-supposed-to-eliminate-those) and the pre-build screen now clearly labels which plugins are going to be masters, which you can double-click on to quickly jump to the same filtered view mentioned in the FAQ.

Hope that helps!

**Closed by focustense** 2021-09-05 00:31 UTC
Labels: bug, duplicate, easynpc

**Comment by Cthulyn** [comment] 2021-09-05 01:12
Thank you so much for the prompt & detailed response!

Looks like it's working now! I looked right at that "[Crash after loading profile](https://github.com/focustense/easymod/issues/103)" post earlier but I thought "profiles" were the TXT files manually selected after "plugin selection" so I didn't think it applied to my issue. 

I think my blackface issue may have been related to previous "Plugin not loaded" errors, which I'd been ignoring just to "see what happened" the first few times. I'm not sure what I did differently this time but I'm not seeing that error now. 

Gradually figuring this thing out! Thank you again for all your help & for all that you do! ^_^
