### ISSUE TITLE
Crash on Pack BSA eye texture

### ISSUE THREAD

**Issue by kasubiaj** [focustense/easymod#104] opened 2021-08-30 20:21 UTC
Currently using a modlist from wabbjack and has some npc overhauls I don't want so I used easyNPC before and it worked fine but after the most recent update of the modlist keeps erroring out on packing the BSA for a eye.dds from Northbourne NPCS of Falkreath Hold. Here is the Log file:
[Log_20210830_161726_2229928.txt](https://github.com/focustense/easymod/files/7079396/Log_20210830_161726_2229928.txt)

**Comment by focustense** [comment] 2021-08-30 20:37
I've normally done my testing with v1.2 of NB-F, so I did try updating to v1.3 in case there was an actual mod update that introduced this issue. However, does not seem to be the case. I ran against the newer version of NB and my BSA packed fine. Whatever the problem is seems to have been specifically caused by Wabbajack

Unfortunately, this is very likely going to be beyond my capacity to fix. EasyNPC doesn't directly own most of the BSA archiving code, it's done through interop to the same DLL used by Cathedral Assets Optimizer, which is based on the original BSArch/xEdit. And I don't think the author is going to be very keen to debug and update that right now, because the author is working on migrating to an entirely new framework.

I've been chatting with some of the wabbajack devs about moving over to their BSA code at some point, if they can expose it as a library, but they are not ready yet and I am not ready yet.

Anyway, I don't even see an eye.dds in that mod, so I think this report is incomplete. Where did you get that file name from, and how did you come to this conclusion? The exceptions thrown by libbsarch contain no useful information, so I can't get the actual name or path from there.

Best thing to do would most likely be to hide that file in Mod Organizer, especially if it's overwriting/conflicting with another file. Like if you're talking about eyecubemap.dds for example, it's just a lower-quality version of the same cubemap provided by other mods like TEOB or Quality Cubemaps and you're better off hiding it regardless.

**Comment by focustense** [comment] 2021-08-30 21:59
After some discussion in the Discord chat, it turned out to be a problem with the mod directory setting and consequently, I believe, having 0 meshes to put into the main BSA. I haven't tested, but BSAs probably have to have at least one file.

Since having no files to pack isn't an intended/expect scenario, going to close the issue, but thanks for reporting!

**Closed by focustense** 2021-08-30 21:59 UTC
Labels: wontfix, easynpc
