### ISSUE TITLE
Something went wrong error

### ISSUE THREAD

**Issue by qualityassuance** [focustense/easymod#53] opened 2021-07-20 19:29 UTC
I get that message box directly after it tries to initialize my load order. Here is the log.

https://pastebin.com/b0gFR2v2

**Comment by focustense** [comment] 2021-07-20 19:59
Relevant lines of trace are:

```
2021-07-20 15:23:58.362 -04:00 [INF] Reading NPC records from More Saddles for NFF.esp...
2021-07-20 15:23:58.374 -04:00 [ERR] Exception was not handled
System.NullReferenceException: Object reference not set to an instance of an object.
   at Focus.Apps.EasyNpc.Mutagen.MutagenAdapter.ReadNpcRecords(String pluginName, IDictionary`2 cache)
   at Focus.Apps.EasyNpc.Main.LoaderViewModel`1.GetNpcs()
```

Have not seen this one before, and the log does not give a whole lot to go by this time around. I suppose I will just have to get this mod and see where it's choking.

Meantime, since it is clearly the `More Saddles for NFF.esp` plugin that it's having trouble with, you could try temporarily disabling that plugin, or just unchecking it in EasyNPC's load order confirmation screen, and see if that gets you past this error, as a temporary workaround.

**Comment by focustense** [comment] 2021-07-21 06:31
I installed NFF, More Saddles and More Saddles for NFF, and enabled all these plugins, and was not able to reproduce this error.

Maybe the plugin has been modified from its original download? Alternatively, the actual issue is with some upstream dependency of the mod that has been changed, or is an old version or is somehow different from what I ended up with.

I'm implementing some generic null checks and additional logging for this class, which may resolve the issue, or if not, at least provide some more insight as to where exactly it's happening. I did find a few "unsafe" calls which could be related.

**Comment by qualityassuance** [comment] 2021-07-21 14:57
I tried removing More Saddles for NFF and I got the same error, I was thinking that maybe it was because I'm using a newer version of NFF. However, it did not work. The thing is, my modlist is absolutely massive so it could be a number of mods causing the error. I've noticed things start to get weird when you have tools like this scanning 1000+ mods to work with. Anyways, I appreciate the help. I might try to make a new profile and make the plugin using only the NPC mods. Then once I have it made, I can just install it on my main profile, right?Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: focustense ***@***.***> Date: 7/21/21  2:32 AM  (GMT-05:00) To: focustense/easymod ***@***.***> Cc: qualityassuance ***@***.***>, Author ***@***.***> Subject: Re: [focustense/easymod] Something went wrong error (#53) 
I installed NFF, More Saddles and More Saddles for NFF, and enabled all these plugins, and was not able to reproduce this error.
Maybe the plugin has been modified from its original download? Alternatively, the actual issue is with some upstream dependency of the mod that has been changed, or is an old version or is somehow different from what I ended up with.
I'm implementing some generic null checks and additional logging for this class, which may resolve the issue, or if not, at least provide some more insight as to where exactly it's happening. I did find a few "unsafe" calls which could be related.

**Comment by focustense** [comment] 2021-07-21 15:03
I suggest you wait a day, two days at most, for 0.8.7 to go out, and see if the linked commit fixes it for you. Unfortunately, due to a bug in .NET 5 itself, there's no way for me to get line numbers out of the stack trace, but I think I've eliminated every possible location where there _could_ be a `NullReferenceException` in that file.

**Comment by focustense** [comment] 2021-07-24 20:24
0.8.7 has been out for a bit now, and 0.8.8 is coming shortly, so I'm closing this issue. If you still encounter it with the latest version, please reopen with details.

**Closed by focustense** 2021-07-24 20:24 UTC
Labels: bug, easynpc
