### ISSUE TITLE
Support for Skyrim VR

### ISSUE THREAD

**Issue by Xerlith** [focustense/easymod#32] opened 2021-07-17 21:34 UTC
![image](https://user-images.githubusercontent.com/10631248/126049669-861d00fe-7584-417a-97c4-88b8d0991955.png)

1. I run the EasyNPC utility from MO2 as described
2. Expected result - the list of actually enabled plugins for the currently selected game appears.
3. Actual result - The list of plugins seems to point at the SkyrimSE directory, without the ability to change targets.

As a secondary attempt (separate drives for isntalled mods and MO2 data: the mods are on an SSD, the same as the Skyrim installation and the MO2 data on a separate HDD), I created a symlink in the MO2 BASEDIR and pointed EasyNPC to that instead, with the same resuilt.

**Comment by Xerlith** [comment] 2021-07-17 21:47
[Profile.log](https://github.com/focustense/easymod/files/6835340/Profile.log)
[Log_20210717_231755_2923219.txt](https://github.com/focustense/easymod/files/6835341/Log_20210717_231755_2923219.txt)

**Comment by focustense** [comment] 2021-07-17 21:48
Hey, thanks for the report. I will admit that there was effectively no testing done on non-portable instances. Surprisingly, it did not come up even once during the alpha.

Having said that, I've set up a named MO2 instance and installed a few basic plugins, and I haven't been able to repro your issue. It seems to work as expected, showing the plugins for that instance.

Your title is a little bit ambiguous so I'd like to clarify: are you seeing this problem when you run EasyNPC with a named MO2 instance _that is for Skyrim VR_, and you suspect the incompatibility is with one of those things? Or does it mean that you are running a named MO2 instance for Skyrim SE, and it is still not listing the correct plugins?

If it is the first one, then I can confirm: Skyrim VR is _not_ currently supported, nor LE or any instance other than SSE. If it is the latter - if you are seeing this for named MO2 + SSE - then is it possible you have multiple instances of the game installed?

**Comment by Xerlith** [comment] 2021-07-17 23:57
It is indeed for a Skyrim VR instance.

**Comment by focustense** [comment] 2021-07-18 03:24
I assumed Skyrim VR would be very difficult, but a few scattered comments have led me to believe that maybe it is just as simple as changing a few enums here and there. If VR uses fundamentally the same record structure and facegen system as SE, then it might be easy to support.

The big issue for me is that I can't test it. I'd prefer not to do the work unless there are a few people willing to stick around long enough to get over the initial hump, maybe a week or two, and not give up if it doesn't work the first few times. If you're interested in trying out what would essentially be more like an alpha than a beta, let me know, and I'll see what I can do.

By the way, the Face Discoloration Fix is not quite the catch-all solution that many people imagine it to be. It _does_ technically prevent blackface, but it gives you what I call "light blackface" in its place. I think it's really cool that someone was able to make that plugin, but at the same time, you're not missing out on _that_ much by not having it in VR.

**Comment by Xerlith** [comment] 2021-07-18 09:31
" If VR uses fundamentally the same record structure and facegen system as SE, then it might be easy to support."

Essentially, yes. The VR version of the game is just an earlier SE build (without ESL support) and with an added SteamVR renderer.

**Comment by focustense** [comment] 2021-07-20 00:14
I went ahead and converted this into an "official" enhancement request. Since I have no ability to test, I think the code would go in a feature branch, and maybe some out-of-band or even off-GitHub "releases" for alpha testers. I can't justify putting an official release on the Nexus, or even on GitHub, and marking it as stable - but I can put out a test release and collect some feedback.

**Comment by focustense** [comment] 2021-07-20 19:05
Question regarding VR and ESL support - is VR not able to load an ESL-flagged plugin at all, or does it just not treat it as an ESL, making it act like a regular plugin?

For very large overhauls, the BSAs need to be split up, and dummy plugins created in order to make the game load those BSAs. Those dummy plugins have no records, they're just for BSA loading, and they're always ESL-flagged. Will VR ignore these plugins completely and/or crash on start, or will they work normally and simply take up a non-FE slot in the load order?

**Comment by Xerlith** [comment] 2021-07-20 21:59
Any ESL-flagged plugin is being loaded like a regular plugin, subject to the 255 limt.

**Comment by focustense** [comment] 2021-08-16 03:12
Leaving a note for myself on LE support - make sure to update the BSA generator code to use FO3 mode.

**Comment by focustense** [comment] 2021-08-20 03:23
As of 0.9.0 (prerelease), now available here on GitHub, you can specify the game type in the command-line arguments.

The option is, simply, `-g <game>` or `--game <game>`.

Supported arguments for `<game>` are:
- `SkyrimSE` (Special Edition - default behavior)
- `SkyrimVR` (VR, obviously)
- `SkyrimLE` (Oldrim, but I promise nothing about how well this will work, and the BSA format is definitely incompatible)
- `EnderalSE` (Should work the same as Skyrim SE, but never tested)
- `EnderalLE` (Same caveats as Skyrim LE)

Give it a try and see. I still cannot test on anything other than SE myself, but all hard-coded references to SE have been removed, so EasyNPC should support other editions just as well as Mutagen and (for the BSA code) libbsarch can.

**Comment by focustense** [comment] 2021-08-22 21:46
With the "stable" version 0.9.1 released, I'm going to close this out. If you still can't even get the app to start with a VR instance then please reopen the issue, but otherwise, any issues specific to VR should be reported as separate bugs.

**Closed by focustense** 2021-08-22 21:46 UTC
Labels: enhancement, easynpc
