### ISSUE TITLE
Plugin Errors when loading plugins 

### ISSUE THREAD

**Issue by artodl** [focustense/easymod#196] opened 2024-02-01 01:30 UTC
I get "the following plugins have serious errors and cannot be used until the errors are fixed. You may need to contact the mod author for a resolution."
I can't copy/paste the entire error for each plugin, the program just don't let me click it to select and copy, to post it on pastebin so i'll post screenshots here. Each plugin seems to have the same issue, or at least very similar issues/errors. It's weird it also includes the vanilla game and dlcs. EasyNPC always worked fine for me, but at this moment, when i installed skyrim again to mod it again, i think it's valid to note that i downgraded the game, i'm currently playing on .640, the version before the couple last updates. Everything in my game works fine, and i tried cleaning the plugins with SSEEdit to see if would fix anything but it didn't. I use MO2 if it's relevant. 
I have no idea what's causing this 
![Screenshot_55](https://github.com/focustense/easymod/assets/27823949/d06dd4c1-2967-4970-8392-bb8b0454c740)
![Screenshot_56](https://github.com/focustense/easymod/assets/27823949/4f45d561-3641-4a07-850a-9450dc95c133)
![Screenshot_57](https://github.com/focustense/easymod/assets/27823949/af10214b-6710-4e98-8dcb-466ecf81855e)

**Comment by lengelb** [comment] 2024-03-01 08:45
I'm having the same problem. Did you manage to get it sorted out?

**Comment by eeekie128** [comment] 2024-03-07 16:56
I am having this issue as well. I am on the latest 1.6.1170 and using MO2, this is what happens when I try to launch through the executable. It launches outside of MO2 fine, but of course there's no mods.

**Comment by focustense** [comment] 2024-03-07 17:19
`RecordCollisionException` means that a plugin has two records with the same form ID, and that's an invalid plugin. As far as I know, that only happens with a few buggy tools like zMerge, but this cluster of reports might mean there's an actual mod in the wild with this problem. In any case, you'll have to figure out which one it is.

It's not a problem with _all_ plugins, like the screen suggests; that's an old bug in the UI/exception reporting that comes up too rarely to make fixing it a priority. It's probably just one plugin. Check the whole log, which by the way was not included - [follow instructions when submitting bug reports, please](https://github.com/focustense/easymod/wiki/Reporting-Bugs#app-crashes) - and see which plugin(s) were being scanned just before the error happened. The offending plugin will be one that has a log entry for starting but not finishing the analysis.

**Comment by eeekie128** [comment] 2024-03-07 18:55
Thank you, this was helpful. I saw all the masters failing to load and assuming it was a mod manager pathing or file header issue that had to do with AE.

**Comment by focustense** [comment] 2024-03-13 00:50
Closing on the assumption that the last comment means you found/fixed the root cause.

**Closed as completed by focustense** 2024-03-13 00:50 UTC
Labels: easynpc, mod issue
