### ISSUE TITLE
Dewigify option renders a default face in addition to making NPC bald

### ISSUE THREAD

**Issue by ryanmccarthy** [focustense/easymod#89] opened 2021-08-12 12:27 UTC
When an NPC is dewigified and EasyNPC is unable to replace their hair (it should randomly select a gender hair option in this case), their face is also rendered as a generic amalgam instead of whatever face I chose from the overhaul list. Mjoll from Pan/Bijin (whichever has the wig) is a good example.

**Comment by focustense** [comment] 2021-08-12 16:21
Thanks for the report. Good suggestion on randomly picking a hair instead of leaving them bald. I'm not sure if it'll matter for much longer, since when I implement #7 in the next release, it's technically also going to carry over the wigs in any cases where they couldn't be converted. So at the end of the day, you won't even notice the difference between wig and de-wigged.

However, the character you've mentioned does not use a wig in either of those two mods, and the behavior you're describing is not caused by the dewiggifier - in fact not _capable_ of being caused by that code, since the dewiggifier operates on Worn Armors, and if it fails, then has essentially not touched that NPC at all.

If you're getting vanilla-ish faces, then odds are you've left some mods enabled which provide facegens as loose files. That's the most common - and in fact so far _only_ confirmed cause of the EasyNPC-generated mod "not modding" an NPC or leaving them with blackface. You may not be seeing the blackface if you're running a certain SKSE plugin which I won't name here, but is [described on the wiki page](https://github.com/focustense/easymod/wiki/Alternatives#face-discoloration-fix-aka-light-blackface). If that looks like what you're getting, and it sounds exactly like what you described, then that's the reason for it.

Solution for you is to disable the conflicting mods. You should disable all of the original NPC overhauls after creating the merge.

**Comment by ryanmccarthy** [comment] 2021-08-15 00:50
That doesn't seem to have helped. I've disabled absolutely all mods that
alter character appearance (except the 3 ApachiiHair ESMs) and I'm still
encountering cobbled faces. Male->Female Housecarl is an example. One
housecarl looks as they should (as shown in the mod), but another looks
like a pudding faced troglodyte. This is odd because
MBWSFollowerReplacer.esp is both the only mod to alter that character's
appearance and is a master for the EasyNPC esp.

**Comment by focustense** [comment] 2021-08-22 21:41
Dewiggify can no longer leave an NPC bald anymore as of v0.9.0, if it can't find the wig then it will simply fall back to using the Worn Armor as per #7, so I am going to close this as fixed.

In your case, I'm still fairly certain it's an issue with conflicts, otherwise the NPCs would still have correct faces aside from being bald. That means it's got nothing to do with the dewiggifier. A reversion to vanilla face geometry, or any vanilla head parts, can _only_ happen if EasyNPC's facegen is overridden by another mod, usually one with loose files.

Trial-and-error process of disabling mods isn't the way to go there. Use normal conflict-resolution steps, i.e. pick a specific NPC to look at, get their form ID from the console or UESP, turn on archive parsing in Mod Organizer, use the Data tab to find out where the facegen is really coming from, open load order in xEdit to see which plugin has the winning override. If you have all that information, please post it accordingly, either in a new bug or in the discord channel.

Thanks!

**Closed by focustense** 2021-08-22 21:41 UTC
Labels: question, easynpc
